M48
; DRILL file {KiCad 7.0.6} date Tue Jul 25 17:46:23 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-25T17:46:23-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X5.103Y-4.5
X5.203Y-4.5
X5.303Y-4.5
X5.403Y-4.5
X5.503Y-4.5
X5.603Y-4.5
X5.703Y-4.5
X5.803Y-4.5
T0
M30
